### ISSUE TITLE
"Cannot open application"

### ISSUE THREAD

**Issue by jafoal** [msarilar/EDEngineer#153]
Whenever I try to start the setup.exe, I get this error message (may have to do with an incomplete or failed uninstall):

PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

IDENTITIES
	Deployment Identity		: EDEngineer.application, Version=1.0.4.5, Culture=neutral, PublicKeyToken=c7c2cd04d2cdd815, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application resulted in exception. Following failure messages were detected:
		+ Activation failed.
		+ The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2017-01-17 2:18:39 AM] : Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application has started.
	* [2017-01-17 2:18:39 AM] : Processing of deployment manifest has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2017-01-17 2:18:39 AM] System.Deployment.Application.DeploymentException (Activation)
		- Activation failed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.IO.FileNotFoundException
		- The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [2017-01-17 2:18:39 AM]
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0

**Comment by msarilar** [comment]
hey, did you try the couple of points at the end of this wiki page https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues ?

**Comment by jafoal** [comment]
Yup, first thing I tried.

**Comment by msarilar** [comment]
might want to make sure the application isn't visible in the "add/remove programs window" (and uninstalling it if it is) and check this answer on SO : http://stackoverflow.com/a/21427009/1054649

**Comment by jafoal** [comment]
That worked, thank you so much!
