### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by migmad** [msarilar/EDEngineer#167]
After updating to 1.0.4.7 using the earlier version's update check, the app fails to launch. Using Windows 10. Partial crash log follows:
``` 
COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [09/02/2017 10:41:44] : Activation of C:\Users\____\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\EDEngineer\EDEngineer.appref-ms| has started.
	* [09/02/2017 10:41:44] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
	Following errors were detected during this operation.
	* [09/02/2017 10:41:44] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```

**Comment by msarilar** [comment]
try running this:

`rundll32 %windir%\system32\dfshim.dll CleanOnlineAppCache`

**Comment by migmad** [comment]
Didn't work :(

**Comment by msarilar** [comment]
all right then this SO's answer should do the trick: http://stackoverflow.com/questions/21423386/installation-issue-while-using-click-once-deployment/21427009#21427009

**Comment by migmad** [comment]
That worked. Should've checked google before pestering you :v 

Thanks for your help!
