### ISSUE TITLE
Application cannot be started. Contact the application vendor

### ISSUE THREAD

**Issue by Jadus81** [msarilar/EDEngineer#170]
PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: file:///C:/Users/Sean/Desktop/EDEngineer.appref-ms%7C
	Deployment Provider url		: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Sean\Desktop\EDEngineer.appref-ms| resulted in exception. Following failure messages were detected:
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [14/02/2017 21:17:40] : Activation of C:\Users\Sean\Desktop\EDEngineer.appref-ms| has started.
	* [14/02/2017 21:17:40] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
	Following errors were detected during this operation.
	* [14/02/2017 21:17:40] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by msarilar** [comment]
you tried the few bullet points at the end of the wiki page to troubleshoot issues https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues ?

**Comment by Jadus81** [comment]
Thanks for the reply. Turned out to be an easy fix, I used the option when add/removing in control panel "Restore the application to its previous state" Thanks for this brilliant piece of software btw o7
