### ISSUE TITLE
Updated and it will not start

### ISSUE THREAD

**Issue by winestork** [msarilar/EDEngineer#183]
Installed new version and it will not start.  Pop-up[ says "Application cannot be started, Contact the application vendor."

Details below:

PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: file:///C:/Users/fulmerd/AppData/Roaming/Microsoft/Windows/Start%20Menu/Programs/EDEngineer/EDEngineer.appref-ms%7C
	Deployment Provider url		: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\fulmerd\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\EDEngineer\EDEngineer.appref-ms| resulted in exception. Following failure messages were detected:
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [3/10/2017 3:20:30 PM] : Activation of C:\Users\fulmerd\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\EDEngineer\EDEngineer.appref-ms| has started.
	* [3/10/2017 3:20:30 PM] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
	Following errors were detected during this operation.
	* [3/10/2017 3:20:30 PM] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by msarilar** [comment]
http://stackoverflow.com/a/21427009/1054649 should solve the issue

**Comment by winestork** [comment]
That did point me to the source of the issue.  I could not delete Newtonsoft.Json.dll because it was in use by another 3rd party Elite Dangerous application I used.  This application was set to start on boot so it kept locking the file, even after a reboot.  Shutting down this application let me delete this dll and then reinstall EDEngineer..

Thanks for your help!
