### ISSUE TITLE
Application cannot be started. Contact the application vendor

### ISSUE THREAD

**Issue by CMDR-LARCO** [msarilar/EDEngineer#202]
Hi , getting the above message when after downloading the new version.
The detail is as follows:-
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1098.0 built by: NETFXREL4STAGE
	clr.dll 			: 4.6.1098.0 built by: NETFXREL4STAGE
	dfdll.dll 			: 4.6.1098.0 built by: NETFXREL4STAGE
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application
	Deployment Provider url		: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application
	Application url			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/Application%20Files/EDEngineer_1_0_5_6/EDEngineer.exe.manifest

IDENTITIES
	Deployment Identity		: EDEngineer.application, Version=1.0.5.6, Culture=neutral, PublicKeyToken=c7c2cd04d2cdd815, processorArchitecture=msil
	Application Identity		: EDEngineer.exe, Version=1.0.5.6, Culture=neutral, PublicKeyToken=c7c2cd04d2cdd815, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application resulted in exception. Following failure messages were detected:
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [13/04/2017 19:40:14] : Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application has started.
	* [13/04/2017 19:40:14] : Processing of deployment manifest has successfully completed.
	* [13/04/2017 19:40:14] : Installation of the application has started.
	* [13/04/2017 19:40:15] : Processing of application manifest has successfully completed.
	* [13/04/2017 19:40:15] : Found compatible runtime version 4.0.30319.
	* [13/04/2017 19:40:15] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [13/04/2017 19:40:15] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.LockApplicationPath(UInt32 Flags, IDefinitionAppId ApId, IntPtr& Cookie)
			at System.Deployment.Application.ComponentStore.LockApplicationPath(DefinitionAppId definitionAppId)
			at System.Deployment.Application.SubscriptionStore.LockApplicationPath(DefinitionAppId definitionAppId)
			at System.Deployment.Application.FileDownloader.PatchFiles(SubscriptionState subState)
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by msarilar** [comment]
think the first section in the wiki will help you https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues
