### ISSUE TITLE
Unrecoverable Error

### ISSUE THREAD

**Issue by CMDR-LARCO** [msarilar/EDEngineer#205]
Hi, followed your previous advice and uninstalled previous version. New version now downloads but then throws up an Unrecoverable error:-
 ( I am running Windows 7 (64 bit) service pack 1 and I am up to date with windows updates. I am logged in as  the system admin)
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EDEngineer.Views.MainWindow' that matches the specified binding constraints threw an exception. ---> System.TypeLoadException: Could not find Windows Runtime type 'Windows.UI.Notifications.ToastNotification'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
   at EDEngineer.Views.CommanderToasts..ctor(State state, String commanderName)
   at EDEngineer.Views.CommanderViewModel..ctor(String commanderName, IEnumerable`1 logs, Languages languages, List`1 entryDatas)
   at EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by msarilar** [comment]
just pushed a hotfix, should be fine now

**Comment by CMDR-LARCO** [comment]
New version downloaded and started fine. Thank you. I'll have a play with it in the morning.

**Comment by msarilar** [comment]
Hey @CMDR-LARCO and @Worith, I'm going to deploy an update soon but I wanted to make sure the same issue doesn't happen again ; could you guys extract this archive [Release.zip](https://github.com/msarilar/EDEngineer/files/947734/Release.zip) and run the `EDEngineer.exe` in it ? (*not* the `EDEngineer.application`).

Let me know what happens when you toy with the new notification settings window and make sure that you *can't* select "Toast" for any of them

http://i.imgur.com/V0cMLvY.png
