### ISSUE TITLE
Cannot open application, which was previously working.

### ISSUE THREAD

**Issue by PolarBruski** [msarilar/EDEngineer#246]
Currently when opening application I get the message:
"Application cannot be started.  Contact the application vendor."

Clicking on "Details" present this:

PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1648.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: file:///C:/Users/nrued_000/AppData/Roaming/Microsoft/Windows/Start%20Menu/Programs/EDEngineer/EDEngineer.appref-ms%7C
	Deployment Provider url		: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\nrued_000\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\EDEngineer\EDEngineer.appref-ms| resulted in exception. Following failure messages were detected:
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [6/13/2017 3:28:04 PM] : Activation of C:\Users\nrued_000\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\EDEngineer\EDEngineer.appref-ms| has started.
	* [6/13/2017 3:28:04 PM] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
	Following errors were detected during this operation.
	* [6/13/2017 3:28:04 PM] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by PolarBruski** [comment]
Went through troubleshooting and fixed this, my bad.

**Comment by ArghArgh200** [comment]
I'm having this same issue and going through the whole troubleshooting document didn't help at all. Same error:
```
PLATFORM VERSION INFO
	Windows 			: 6.3.9600.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1590.0 built by: NETFXREL2
	clr.dll 			: 4.6.1590.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1590.0 built by: NETFXREL2
	dfshim.dll 			: 6.3.9600.16384 (winblue_rtm.130821-1623)

SOURCES
	Deployment url			: file:///C:/Users/Arghlex/Desktop/EDEngineer.application
	Deployment Provider url		: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application
	Application url			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/Application%20Files/EDEngineer_1_0_8_1/EDEngineer.exe.manifest

IDENTITIES
	Deployment Identity		: EDEngineer.application, Version=1.0.8.1, Culture=neutral, PublicKeyToken=c7c2cd04d2cdd815, processorArchitecture=msil
	Application Identity		: EDEngineer.exe, Version=1.0.8.1, Culture=neutral, PublicKeyToken=c7c2cd04d2cdd815, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Arghlex\Desktop\EDEngineer.application resulted in exception. Following failure messages were detected:
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [7/2/2017 7:32:14 PM] : Activation of C:\Users\Arghlex\Desktop\EDEngineer.application has started.
	* [7/2/2017 7:32:14 PM] : Processing of deployment manifest has successfully completed.
	* [7/2/2017 7:32:14 PM] : Installation of the application has started.
	* [7/2/2017 7:32:14 PM] : Processing of application manifest has successfully completed.
	* [7/2/2017 7:32:15 PM] : Found compatible runtime version 4.0.30319.
	* [7/2/2017 7:32:15 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [7/2/2017 7:32:15 PM] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.LockApplicationPath(UInt32 Flags, IDefinitionAppId ApId, IntPtr& Cookie)
			at System.Deployment.Application.ComponentStore.LockApplicationPath(DefinitionAppId definitionAppId)
			at System.Deployment.Application.SubscriptionStore.LockApplicationPath(DefinitionAppId definitionAppId)
			at System.Deployment.Application.FileDownloader.PatchFiles(SubscriptionState subState)
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```
