### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by Ferr8** [msarilar/EDEngineer#252]
Hi,
I got an error message that asked me to raise an issue.  It won't let me select the text to copy and paste, so I will uipload it as a screen shot.
Thanks!
![image](https://user-images.githubusercontent.com/29740574/27610828-ca1dfc36-5b87-11e7-8576-cef5d67bb01a.png)

Edit: after clicking, OK, I get a second error:
![image](https://user-images.githubusercontent.com/29740574/27610870-fbeca1fe-5b87-11e7-864b-fc96cca1e571.png)

**Comment by aylesj** [comment]
Same problem. I would guess that EngineerContribution is a new event type added in v2.3.10

---------------------------
Error
---------------------------
Something went wrong in parsing your logs, open an issue on GitHub with this information : 

LogEntry = {
  "timestamp": "2017-06-27T22:40:06Z",
  "event": "EngineerContribution",
  "Engineer": "The Sarge",
  "Type": "Materials",
  "Material": "shieldpatternanalysis",
  "Quantity": 27,
  "TotalQuantity": 41
}

Error:System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at EDEngineer.Utils.ItemNameConverter.TryGet(String key, String& name)
   at EDEngineer.Utils.JournalEntryConverter.ExtractEngineerContribution(JObject data)
   at EDEngineer.Utils.JournalEntryConverter.ExtractOperation(JObject data, JournalEvent journalEvent)
   at EDEngineer.Utils.JournalEntryConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
---------------------------
OK   
---------------------------

**Comment by Ferr8** [comment]
Ah yes, you are right! I checked the patch notes and see:
"New "EngineerContribution" event for making donations to unlock an Engineer"

**Comment by msarilar** [comment]
thanks for bringing that up, that should be fine now !

**Comment by aylesj** [comment]
Thanks for prompt response. Quick test shows error is fixed.
