### ISSUE TITLE
Unrecoverable Error

### ISSUE THREAD

**Issue by CMDR-K** [msarilar/EDEngineer#295]
Been using this great program a lot past 6 months. I am suddenly getting this error. Have tried to reinstall with no luck. Here's the message I keep getting. I can't hardly stand engineering without EDEngineers! And now I've got a Type 10 to work on! Any help greatly appreciated.

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EDEngineer.Views.MainWindow' that matches the specified binding constraints threw an exception. ---> System.Configuration.ConfigurationErrorsException: Failed to save settings: An error occurred loading a configuration file: Unable to open file 'C:\Users\Frank\AppData\Local\Apps\2.0\Data\GXJQVHND.W39\LA4LQT69.DZE\eden..tion_c7c2cd04d2cdd815_0001.0000_7e219bf705d9d57b\Data\1.0.0.0\user.config' for writing because it is read-only or hidden. (C:\Users\Frank\AppData\Local\Apps\2.0\Data\GXJQVHND.W39\LA4LQT69.DZE\eden..tion_c7c2cd04d2cdd815_0001.0000_7e219bf705d9d57b\Data\1.0.0.0\user.config) ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Unable to open file 'C:\Users\Frank\AppData\Local\Apps\2.0\Data\GXJQVHND.W39\LA4LQT69.DZE\eden..tion_c7c2cd04d2cdd815_0001.0000_7e219bf705d9d57b\Data\1.0.0.0\user.config' for writing because it is read-only or hidden. (C:\Users\Frank\AppData\Local\Apps\2.0\Data\GXJQVHND.W39\LA4LQT69.DZE\eden..tion_c7c2cd04d2cdd815_0001.0000_7e219bf705d9d57b\Data\1.0.0.0\user.config) ---> System.IO.IOException: Unable to open file 'C:\Users\Frank\AppData\Local\Apps\2.0\Data\GXJQVHND.W39\LA4LQT69.DZE\eden..tion_c7c2cd04d2cdd815_0001.0000_7e219bf705d9d57b\Data\1.0.0.0\user.config' for writing because it is read-only or hidden.
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.Internal.DelegatingConfigHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.UpdateConfigHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.Configuration.SaveAsImpl(String filename, ConfigurationSaveMode saveMode, Boolean forceSaveAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at EDEngineer.Utils.System.SettingsManager.set_Comparer(String value)
   at EDEngineer.Views.MainWindowViewModel.set_CurrentComparer(String value)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by msarilar** [comment]
not exactly sure what's wrong, I would just delete the file at `C:\Users\Frank\AppData\Local\Apps\2.0\Data\GXJQVHND.W39\LA4LQT69.DZE\eden..tion_c7c2cd04d2cdd815_0001.0000_7e219bf705d9d57b\Data\1.0.0.0\user.config` since it seems to be hidden/readonly (or somehow corrupted)

you'll lose all your settings however but it's easy to reconfigure the app
