### ISSUE TITLE
Cant Launch ED Engineer

### ISSUE THREAD

**Issue by TheFalkenrath** [msarilar/EDEngineer#310]
Hey guys, came back to ED after a few months break, launched ED engineer and it updated, followed by not launching. Last time this happened I found the original application (cant remember where) in Program Files or App Data and launched from there, no problem. Except any ED engineer folder I now open is completely empty, Minus the start menu folder. Any help would be welcome!

**Comment by msarilar** [comment]
try to uninstall like this :

![image](https://user-images.githubusercontent.com/5569959/36935387-8f6b9a60-1ef7-11e8-8fab-77bcbb94d579.png)

and reinstall afterwards

**Comment by BarryCarlyon** [comment]
I also have this issue.

I uninstalled and reinstalled (via programs list)

I did see the "language" and "notification" setup then nothing

**Comment by msarilar** [comment]
make sure the application is visible here:

![image](https://user-images.githubusercontent.com/5569959/36935463-4f455b82-1ef8-11e8-8ccf-0479642ae558.png)

if it still doesn't show, you can also try the "Reset Window Position"

**Comment by BarryCarlyon** [comment]
There is no Taskbar icon.

And nothing in Task Manager to indicate the program is still running

**Comment by msarilar** [comment]
Could you search for EDEngineer logs in the event manager?

![image](https://user-images.githubusercontent.com/5569959/36935538-5c2e0442-1ef9-11e8-8d18-f0ce85d66f31.png)

![image](https://user-images.githubusercontent.com/5569959/36935551-7d9177f4-1ef9-11e8-9265-442b934d4a83.png)

there might be some clues for what's going wrong

**Comment by BarryCarlyon** [comment]
we got some. Fetching logs now

**Comment by BarryCarlyon** [comment]
`Application: EDEngineer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at MS.Win32.UnsafeNativeMethods.CreateWindowEx(Int32, System.String, System.String, Int32, Int32, Int32, Int32, Int32, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Object)
   at MS.Win32.HwndWrapper..ctor(Int32, Int32, Int32, Int32, Int32, Int32, Int32, System.String, IntPtr, MS.Win32.HwndWrapperHook[])
   at System.Windows.Interop.HwndSource.Initialize(System.Windows.Interop.HwndSourceParameters)
   at System.Windows.Window.CreateSourceWindow(Boolean)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(System.Object)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at EDEngineer.App+<>c.<.ctor>b__0_1(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
   at System.Windows.Threading.Dispatcher.CatchException(System.Exception)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(System.Object, System.Exception)
   at System.Windows.Threading.ExceptionWrapper.CatchException(System.Object, System.Exception, System.Delegate)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
`

`Faulting application name: EDEngineer.exe, version: 1.0.0.0, time stamp: 0x5a9aad32
Faulting module name: KERNELBASE.dll, version: 10.0.16299.248, time stamp: 0x13ae3814
Exception code: 0xe0434352
Fault offset: 0x001008c2
Faulting process ID: 0x5fc
Faulting application start time: 0x01d3b2fe346c5b01
Faulting application path: C:\Users\barry\AppData\Local\Apps\2.0\39WPXMTG.MZX\GM9EYG0Q.0W0\eden..tion_b9c6c2d0b4f2eae5_0001.0000_ad1ebda99dd40b63\EDEngineer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 69898891-6c3f-4153-8db8-a89d6ba73c1a
Faulting package full name: 
Faulting package-relative application ID: `

`Fault bucket 1449411363250274940, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: EDEngineer.exe
P2: 1.0.0.0
P3: 5a9aad32
P4: WindowsBase
P5: 4.7.2633.0
P6: 5a4edefc
P7: d3
P8: 2c
P9: System.ComponentModel.Win32
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6866.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6C11.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6C1F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6C30.tmp.txt
\\?\C:\Users\barry\AppData\Local\Temp\WER72AA.tmp.appcompat.txt
\\?\C:\Users\barry\AppData\Local\Temp\WER72BB.tmp.WERDataCollectionStatus.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_EDEngineer.exe_f315ca2a224fdf528ac7143767b473dd8692bac_6ad79bfc_197072c6

Analysis symbol: 
Rechecking for solution: 0
Report ID: 69898891-6c3f-4153-8db8-a89d6ba73c1a
Report Status: 2147487752
Hashed bucket: 84a9abaac6a166cef41d57f49ff2827c`

`Faulting application name: EDEngineer.exe, version: 1.0.0.0, time stamp: 0x5a9aad32
Faulting module name: KERNELBASE.dll, version: 10.0.16299.248, time stamp: 0x13ae3814
Exception code: 0xc000041d
Fault offset: 0x001008c2
Faulting process ID: 0x5fc
Faulting application start time: 0x01d3b2fe346c5b01
Faulting application path: C:\Users\barry\AppData\Local\Apps\2.0\39WPXMTG.MZX\GM9EYG0Q.0W0\eden..tion_b9c6c2d0b4f2eae5_0001.0000_ad1ebda99dd40b63\EDEngineer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 8656e48c-df8b-447d-ae19-1c68af4f7455
Faulting package full name: 
Faulting package-relative application ID: `

`Fault bucket 1806596678092420382, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: EDEngineer.exe
P2: 1.0.0.0
P3: 5a9aad32
P4: KERNELBASE.dll
P5: 10.0.16299.248
P6: 13ae3814
P7: c000041d
P8: 001008c2
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7547.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7921.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7921.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7941.tmp.txt
\\?\C:\Users\barry\AppData\Local\Temp\WER8160.tmp.appcompat.txt
\\?\C:\Users\barry\AppData\Local\Temp\WER8170.tmp.WERDataCollectionStatus.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_EDEngineer.exe_4835481788e6e9dfc275821a5ee3c1627eb4_6ad79bfc_53f4817c

Analysis symbol: 
Rechecking for solution: 0
Report ID: 8656e48c-df8b-447d-ae19-1c68af4f7455
Report Status: 2147487752
Hashed bucket: 7c1fca23e5fc212e6912521b6219751e`

**Comment by JohnXaverius** [comment]
Same problem

![clipboard01](https://user-images.githubusercontent.com/29731838/36935621-4d38ea64-1efa-11e8-8cc4-c6aa56efdb86.jpg)
.

**Comment by msarilar** [comment]
could you upload your logs as a zip file here?

**Comment by JohnXaverius** [comment]
No problem. Here :)
[ErrorLog.zip](https://github.com/msarilar/EDEngineer/files/1777564/ErrorLog.zip)

**Comment by msarilar** [comment]
No sorry I meant your logs from Elite Dangerous, i.e. the journal logs (see the path I've added)

**Comment by JohnXaverius** [comment]
:)
[Logs.zip](https://github.com/msarilar/EDEngineer/files/1777569/Logs.zip)

**Comment by msarilar** [comment]
Cheers, I've just published a patch that should fix the problem let me know if that's all right now.

Seems there's many new ingredients that EDEngineer is not aware of, you'll see them in the Unkown category (the ones that the app doesn't know about have an interrogation mark `?` instead of their rarity and their name is the technical name appearing in the logs).

I think at some point we might want to add them to the entry list like the thargoid materials https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/entryData.json#L1130

**Comment by JohnXaverius** [comment]
Now working properly.
![clipboard01](https://user-images.githubusercontent.com/29731838/36935831-01e8ad1c-1efd-11e8-8861-795ca5574837.jpg)

**Comment by BarryCarlyon** [comment]
+1

**Comment by TheFalkenrath** [comment]
Okay, So I went ahead and tried to boot it this morning again before going through the steps in this thread, this time I got an update, after the update ran successfully error that was submitted to windows, apparently I failed to take a screen shot but this is what the log showed. Let me know if more information is required.

Log Name:      Application
Source:        Application Error
Date:          3/3/2018 10:11:55 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      HomeTerminal
Description:
Faulting application name: EDEngineer.exe, version: 1.0.0.0, time stamp: 0x5a9ab7ca
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x2cd1ce3d
Exception code: 0xe0434352
Fault offset: 0x001008b2
Faulting process id: 0x39d0
Faulting application start time: 0x01d3b31b17302365
Faulting application path: C:\Users\Falkenrath\AppData\Local\Apps\2.0\NL0HVO11.7QW\8DDTRY3Z.ZPV\eden..tion_b9c6c2d0b4f2eae5_0001.0000_ae1cdd20995c7da3\EDEngineer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7793f7ab-2ee3-4c5f-9355-4f50507be0a6
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-03-03T18:11:55.349030600Z" />
    <EventRecordID>9294</EventRecordID>
    <Channel>Application</Channel>
    <Computer>HomeTerminal</Computer>
    <Security />
  </System>
  <EventData>
    <Data>EDEngineer.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>5a9ab7ca</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.16299.15</Data>
    <Data>2cd1ce3d</Data>
    <Data>e0434352</Data>
    <Data>001008b2</Data>
    <Data>39d0</Data>
    <Data>01d3b31b17302365</Data>
    <Data>C:\Users\Falkenrath\AppData\Local\Apps\2.0\NL0HVO11.7QW\8DDTRY3Z.ZPV\eden..tion_b9c6c2d0b4f2eae5_0001.0000_ae1cdd20995c7da3\EDEngineer.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>7793f7ab-2ee3-4c5f-9355-4f50507be0a6</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          3/3/2018 10:11:54 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      HomeTerminal
Description:
Application: EDEngineer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at EDEngineer.Properties.Settings.get_Language()
   at EDEngineer.Localization.Languages.InitLanguages()
   at EDEngineer.Localization.Languages.get_Instance()
   at EDEngineer.Views.Popups.ErrorWindow..ctor(System.Exception)
   at EDEngineer.App+<>c.<.ctor>b__0_0(System.Object, System.UnhandledExceptionEventArgs)


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-03-03T18:11:54.625022600Z" />
    <EventRecordID>9293</EventRecordID>
    <Channel>Application</Channel>
    <Computer>HomeTerminal</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: EDEngineer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at EDEngineer.Properties.Settings.get_Language()
   at EDEngineer.Localization.Languages.InitLanguages()
   at EDEngineer.Localization.Languages.get_Instance()
   at EDEngineer.Views.Popups.ErrorWindow..ctor(System.Exception)
   at EDEngineer.App+&lt;&gt;c.&lt;.ctor&gt;b__0_0(System.Object, System.UnhandledExceptionEventArgs)

</Data>
  </EventData>
</Event>

**Comment by msarilar** [comment]
@TheFalkenrath so this is a different issues than the one the other guys got ; looks like an issue with your settings. Did you try to reinstall just in case it solves the issue?

**Comment by Croniat** [comment]
> quand je clic en haut à droite sur les matériaux pour l'enregistrer sur EDEngineers, ça me dit que mon API n'est pas en route.
> 
> pourrais tu m'expliquer comment faire.?

Salut,
J'espère que tu as eu une réponse depuis... au cas où ça servirait à quelqu'un d'autre, moi j'ai changé pour 44410 le port et depuis API ON (vérifie bien aussi que ton firewall autorise bien ce logiciel à discuter sur ce port)
Bien à toi

**Comment by stoun09** [comment]
> À bientôt, je viens de publier un patch qui devrait résoudre le problème, faites-moi savoir si tout va bien maintenant.
> 
> Il semble qu'il y ait de nombreux nouveaux ingrédients dont EDEngineer n'est pas au courant, vous les verrez dans la catégorie inconnue (ceux que l'application ne connaît pas ont un point d'interrogation `?`au lieu de leur rareté et leur nom est le nom technique apparaissant dans le journaux).
> 
> Je pense qu'à un moment donné, nous pourrions vouloir les ajouter à la liste d'entrées comme les matériaux thargoïdes https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/entryData.json#L1130

after several months of absence on ED, I wanted to go back there but when I install ED engineers it does not launch and seeing that I am bad at data processing I did not understand how to use the fix which you published.

**Comment by stoun09** [comment]
> A bientôt, je viens de publier un patch qui devrait résoudre le problème, faites-moi savoir si tout va bien maintenant.
> 
> Il semble qu'il y ait de nombreux nouveaux ingrédients dont EDEngineer n'est pas au courant, vous les verrez dans la catégorie inconnue (ceux que l'application ne connaît pas ont un point d'interrogation `?`au lieu de leur rareté et leur nom est le nom technique apparaissant dans le journaux).
> 
> Je pense qu'à un moment donné, nous pourrions vouloir les ajouter à la liste d'entrées comme les matériaux thargoïdes https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/entryData.json#L1130



> essayez de désinstaller comme ceci:
> 
> ![image](https://user-images.githubusercontent.com/5569959/36935387-8f6b9a60-1ef7-11e8-8fab-77bcbb94d579.png)
> 
> et réinstaller ensuite

salut max , je ne sais pas comment te contacter j’espère que t'aura mon message mais j'ai un souci avec ED engineers , je l'installe sans problème mais impossible a lancé j'ai chercher partout je n'ai pas pu trouver une solution du coup je me retourne vers toi , voila je te laisse mes journaux d'elite.
[Elite Dangerous.zip](https://github.com/msarilar/EDEngineer/files/4617663/Elite.Dangerous.zip)

**Comment by msarilar** [comment]
salut, pour moi ça marche bien tes logs :
![image](https://user-images.githubusercontent.com/5569959/82040850-84351e80-96a7-11ea-8eb0-9130d5d55ac1.png)


essayes de désinstaller puis supprimer tout dossier EDEngineer dans AppData/Local et AppData/Roaming

et enfin essayes d'installer l'app avec le setup.exe

tu peux aussi vérifier dans le tasktray si il y a l'icône EDEngineer : clique droit dessus et "Reset Window Position"

**Comment by stoun09** [comment]
c'est bon merci max , j'ai réussi après avoir poster le message a le lancé.
j'avais juste besoin de mettre a jour mes pilotes ^^.
