### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by bjornthv** [msarilar/EDEngineer#320]
Just updated, tried to launch it and it threw an error:

`System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EDEngineer.Views.MainWindow' that matches the specified binding constraints threw an exception. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EDEngineer.Models.State..ctor(List`1 entryDatas, ILanguage languages, String comparer)
   at EDEngineer.Views.CommanderViewModel..ctor(String commanderName, IEnumerable`1 logs, Languages languages, List`1 entryDatas)
   at EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by bjornthv** [comment]
And yes, I have tried all the steps as described in the guide: https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues

**Comment by bjornthv** [comment]
After finishing the troubleshooting guide, I get the "Application cannot be started. Contact the application vendor" screen. 

Under details, I get:

`PLATFORM VERSION INFO
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2633.0 built by: NET471REL1LAST_C
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

SOURCES
	Deployment url			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application resulted in exception. Following failure messages were detected:
		+ The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [6-3-2018 06:28:49] : Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [6-3-2018 06:28:58] System.Runtime.InteropServices.COMException
		- The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.GetAssemblyInformation(UInt32 Flags, IDefinitionIdentity DefinitionIdentity, Guid& riid)
			at System.Deployment.Internal.Isolation.Store.GetAssemblyManifest(UInt32 Flags, IDefinitionIdentity DefinitionIdentity)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestFromStore(DefinitionIdentity asmId)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestWithRetry(DefinitionIdentity asmId, TimeSpan retryInterval, Int32 maxRetryCount)
			at System.Deployment.Application.ComponentStore.GetSubscriptionStateInternal(DefinitionIdentity subId)
			at System.Deployment.Application.SubscriptionStore.GetSubscriptionStateInternal(SubscriptionState subState)
			at System.Deployment.Application.SubscriptionStore.CheckAndReferenceApplication(SubscriptionState subState, DefinitionAppId appId, Int64 transactionId)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.`

**Comment by msarilar** [comment]
could you upload your logs as a zip file here?

**Comment by bjornthv** [comment]
That is the problem; The program doesn't initiate, there are no logs other than the ones posted above.

**Comment by msarilar** [comment]
I meant your Elite Dangerous logs (copy past this in a file explorer address: `C:\Users\%USERNAME%\Saved Games\Frontier Developments\Elite Dangerous`)

**Comment by bjornthv** [comment]
Give me a moment, I will upload them.

**Comment by bjornthv** [comment]
Done: [Elite Dangerous.zip](https://github.com/msarilar/EDEngineer/files/1783991/Elite.Dangerous.zip)

**Comment by msarilar** [comment]
all right it's actually not related to your logs but the issue was easy to fix
you'll have to wait tonight though for a hotfix but you can manually fix this by going in:

`C:\Users\%USERNAME%\AppData\Local\EDEngineer` then find a folder like `EDEngineer.exe_[.....]` and browse until you find a file `user.config`

look for this setting:

```xml
            <setting name="Comparer" serializeAs="String">
                <value>Threshold</value>
            </setting>
```

and change `Threshold` to `Count`

**Comment by bjornthv** [comment]
Awesome, I'll go and do that now 👍

**Comment by msarilar** [comment]
fix published
