### ISSUE TITLE
Stuck with new version 1.1.1.6

### ISSUE THREAD

**Issue by Uriei** [msarilar/EDEngineer#361]
I've just updated the app and it didn't do anything, no taskbar icon, no response to hotkey, just a zombie process, after a few tries I uninstalled it and reinstalled it, now it does the same but now includes a splash screen that won't go away until I kill the process, which BTW was hard because the splash was on top of everything.

![image](https://user-images.githubusercontent.com/6078221/38413611-8530fe5a-398c-11e8-865e-19256068a208.png)

**Comment by Uriei** [comment]
I've just tried the troubleshooting page solutions and now I only get this.
`PLATFORM VERSION INFO
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2633.0 built by: NET471REL1LAST_C
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

SOURCES
	Deployment url			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application resulted in exception. Following failure messages were detected:
		+ The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [06-Apr-18 11:28:48 AM] : Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [06-Apr-18 11:28:57 AM] System.Runtime.InteropServices.COMException
		- The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.GetAssemblyInformation(UInt32 Flags, IDefinitionIdentity DefinitionIdentity, Guid& riid)
			at System.Deployment.Internal.Isolation.Store.GetAssemblyManifest(UInt32 Flags, IDefinitionIdentity DefinitionIdentity)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestFromStore(DefinitionIdentity asmId)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestWithRetry(DefinitionIdentity asmId, TimeSpan retryInterval, Int32 maxRetryCount)
			at System.Deployment.Application.ComponentStore.GetSubscriptionStateInternal(DefinitionIdentity subId)
			at System.Deployment.Application.SubscriptionStore.GetSubscriptionStateInternal(SubscriptionState subState)
			at System.Deployment.Application.SubscriptionStore.CheckAndReferenceApplication(SubscriptionState subState, DefinitionAppId appId, Int64 transactionId)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

`

**Comment by msarilar** [comment]
could you take a look at the event log as described here ? https://github.com/msarilar/EDEngineer/issues/310#issuecomment-370152359

maybe there's some better information in here

**Comment by Uriei** [comment]
I see nothing that mentions EDEngineer, I tried with the "Find" option and nothing.

![image](https://user-images.githubusercontent.com/6078221/38415719-ab5ac704-3992-11e8-8c32-5b2b7a24d795.png)

**Comment by msarilar** [comment]
all right could you make sure you have .NET 4.6.1 installed ?

https://www.microsoft.com/download/details.aspx?id=49982

**Comment by Uriei** [comment]
Ok, I've solved the installation problem deleting completely the contents of the folder `%userprofile%\Local Settings\Apps` and now I have the splash screen again, but just the splash, for now it's been a minute and it isn't gone yet.

**Comment by msarilar** [comment]
ok, as a last resort could you try this ? 

https://www.microsoft.com/fr-fr/download/details.aspx?id=13450

**Comment by Uriei** [comment]
Nothing, I've installed that, and reinstalled EDEngineer afterwards, still stuck in the splash screen.

**Comment by msarilar** [comment]
please try with the new update
it won't fix your problem but you'll get at least an error message

**Comment by Searcher13** [comment]
Windows10 x64 ver. 17133.1
until yesterday the program was not confused, and yesterday, about a miracle, the program started and worked perfectly. but after today's update again nothing works, the ClickOnce process hangs in the background and nothing happens.

**Comment by msarilar** [comment]
All right I suspect the new zip file embedded to compress the data is causing these issues... I understand it could be considered suspect by Windows or any AV (it takes a zip file, unzip it, read the json extracted, then delete the zip and the files once the content is in memory) but that saved a few megabytes.

I'm removing that for now, patch is deployed.

**Comment by Uriei** [comment]
Unrecoverable error

```System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ApplyNativeSettings(IFileDialog dialog)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at EDEngineer.Utils.System.IOUtils.RetrieveLogDirectory(Boolean forcePickFolder, String currentLogDirectory)
   at EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow.<.ctor>b__3_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ApplyNativeSettings(IFileDialog dialog)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at EDEngineer.Utils.System.IOUtils.RetrieveLogDirectory(Boolean forcePickFolder, String currentLogDirectory)
   at EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow.<.ctor>b__3_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by msarilar** [comment]
should be right now :)

**Comment by msarilar** [comment]
great!
