### ISSUE TITLE
UNRECOVERABLE ERROR

### ISSUE THREAD

**Issue by badbud65** [msarilar/EDEngineer#365]
I keep getting the error below. I have uninstalled and Reinstalled EDEngineer but I still get the error and as such EDEngineer won't now load.

```System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at EDEngineer.Models.Operations.DumpOperation.Mutate(State state)
   at EDEngineer.Views.CommanderViewModel.MutateState(JournalEntry entry)
   at EDEngineer.Views.CommanderViewModel.ApplyEventsToSate(IEnumerable`1 allLogs)
   at EDEngineer.Views.CommanderViewModel.LoadState(IEnumerable`1 events)
   at EDEngineer.Views.CommanderViewModel..ctor(String commanderName, IEnumerable`1 logs, Languages languages, List`1 entryDatas)
   at EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow.<.ctor>b__3_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at EDEngineer.Models.Operations.DumpOperation.Mutate(State state)
   at EDEngineer.Views.CommanderViewModel.MutateState(JournalEntry entry)
   at EDEngineer.Views.CommanderViewModel.ApplyEventsToSate(IEnumerable`1 allLogs)
   at EDEngineer.Views.CommanderViewModel.LoadState(IEnumerable`1 events)
   at EDEngineer.Views.CommanderViewModel..ctor(String commanderName, IEnumerable`1 logs, Languages languages, List`1 entryDatas)
   at EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow.<.ctor>b__3_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by msarilar** [comment]
should be all right after restart
