### ISSUE TITLE
Standalone version desnt work

### ISSUE THREAD

**Issue by eaglepigjim** [msarilar/EDEngineer#366]
Hi,

For us poor schumks on an Xbox, this doesnt work in standalone anymore. It  throws the following error fter you cncel the find log folder dialog.

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ApplyNativeSettings(IFileDialog dialog)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at EDEngineer.Utils.System.IOUtils.RetrieveLogDirectory(Boolean forcePickFolder, String currentLogDirectory)
   at EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow.<.ctor>b__3_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ApplyNativeSettings(IFileDialog dialog)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.ShowDialog()
   at EDEngineer.Utils.System.IOUtils.RetrieveLogDirectory(Boolean forcePickFolder, String currentLogDirectory)
   at EDEngineer.Views.MainWindowViewModel.LoadState(Boolean forcePickFolder)
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages)
   at EDEngineer.Views.MainWindow.<.ctor>b__3_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Thanks

**Comment by msarilar** [comment]
should be all right now, thanks for reporting
