### ISSUE TITLE
Local API crash

### ISSUE THREAD

**Issue by Thurion** [msarilar/EDEngineer#421]
I started EdEngineer 1.1.2.8 and started the local API on the default port. When I click on "launch local API" again, I get this error:
```
System.AggregateException: One or more errors occurred. ---> System.OperationCanceledException: The operation was canceled.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Suave.Web.startWebServer(SuaveConfig config, FSharpFunc`2 webpart)
   at Server.start(CancellationToken token, Int32 port, ILanguage translator, Func`1 state, Func`1 shopppingLists, Action`3 changeShoppingList)
   at EDEngineer.Utils.System.ServerBridge.<>c__DisplayClass8_0.<Start>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.OperationCanceledException: The operation was canceled.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Suave.Web.startWebServer(SuaveConfig config, FSharpFunc`2 webpart)
   at Server.start(CancellationToken token, Int32 port, ILanguage translator, Func`1 state, Func`1 shopppingLists, Action`3 changeShoppingList)
   at EDEngineer.Utils.System.ServerBridge.<>c__DisplayClass8_0.<Start>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by msarilar** [comment]
This is not actually an error and shouldn't be handled like it is, but before I fix this don't worry about it. It just means you stopped local API (if you enable the local API and you click again on the menu item, it will stop it).
