### ISSUE TITLE
"Application Cannot Be Started" after updating

### ISSUE THREAD

**Issue by Synoxys** [msarilar/EDEngineer#433]
When I updated EDEngineer today and tried to run it, I got this error message. I clicked the "Details..." button and was presented with this: https://pastebin.com/taHwJhdV

**Comment by Synoxys** [comment]
Unfortunately, I ran through that list and got no results with any of the methods suggested. I have also done a full manual uninstall. All EDEngineer files were permanently deleted from my disk. The registry key for EDEngineer was deleted. It was as if the application was never there (except I did save the .json file with my adjustments in it). I attempted to reinstall using the latest EDEngineer version's setup.exe and it gave me the same dialog box. However, the log was slightly different. https://pastebin.com/0uXdMY6L

Really love the app and I would like to be able to use it again, so any insight is appreciated!

**Comment by msarilar** [comment]
what happens if you save this file (ctrl+S in your browser) and open it ? [EDEngineer.application](https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application)

**Comment by Synoxys** [comment]
It gives the same dialog box and gives me this log if I press "Details..." https://pastebin.com/xe8tVHbR

**Comment by Cygnus80** [comment]
I get the following error whenever I try to run the program.

I've gone through all of the trouble shooting and am still getting this error.

I'm running Windows7.

```PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2634.0 built by: NET471REL1LAST_C
	clr.dll 			: 4.7.2650.0 built by: NET471REL1LAST_B
	dfdll.dll 			: 4.7.2634.0 built by: NET471REL1LAST_C
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application resulted in exception. Following failure messages were detected:
		+ The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [27/08/2018 6:12:46 PM] : Activation of https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [27/08/2018 6:12:55 PM] System.Runtime.InteropServices.COMException
		- The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.GetAssemblyInformation(UInt32 Flags, IDefinitionIdentity DefinitionIdentity, Guid& riid)
			at System.Deployment.Internal.Isolation.Store.GetAssemblyManifest(UInt32 Flags, IDefinitionIdentity DefinitionIdentity)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestFromStore(DefinitionIdentity asmId)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestWithRetry(DefinitionIdentity asmId, TimeSpan retryInterval, Int32 maxRetryCount)
			at System.Deployment.Application.ComponentStore.GetSubscriptionStateInternal(DefinitionIdentity subId)
			at System.Deployment.Application.SubscriptionStore.GetSubscriptionStateInternal(SubscriptionState subState)
			at System.Deployment.Application.SubscriptionStore.CheckAndReferenceApplication(SubscriptionState subState, DefinitionAppId appId, Int64 transactionId)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.```

**Comment by le0lan** [comment]
Hey, 
I get the same error whenever I try to install the tool.
I did everything in the Troubleshooting-guide, but nothing worked for me...
[https://pastebin.com/dH60v2xG]
