### ISSUE TITLE
cannot Run/ install program

### ISSUE THREAD

**Issue by Timnus** [msarilar/EDEngineer#487]
opened program. been over 8 months since last opening.  would not update. folllowed the steps shown on

https://github.com/msarilar/EDEngineer/wiki/Troubleshooting-Issues 

even ran cCleaner. cannot get program to properly install or run

[4IZ8J19P.log](https://github.com/msarilar/EDEngineer/files/2761138/4IZ8J19P.log)
![edengineererror01152019](https://user-images.githubusercontent.com/27913772/51205003-91cb7000-18ca-11e9-816f-3377ec899f04.JPG)

**Comment by Timnus** [comment]
more trouble trying to install. 
![edengineererror011302019](https://user-images.githubusercontent.com/27913772/51980480-ca845100-2455-11e9-87d0-95ebdf6b1b73.JPG)

**Comment by Timnus** [comment]
[5Z12PJ9M.log](https://github.com/msarilar/EDEngineer/files/2812599/5Z12PJ9M.log)

**Comment by Timnus** [comment]
more trouble trying to install. 
![edengineererror011302019](https://user-images.githubusercontent.com/27913772/51980480-ca845100-2455-11e9-87d0-95ebdf6b1b73.JPG)

**Comment by Timnus** [comment]
tried that and still get same error.

**Comment by msarilar** [comment]
it's possible .NET 4.6.1 (required for the application) isn't properly installed

you can get the latest version of .NET here https://dotnet.microsoft.com/download/dotnet-framework-runtime/net472

**Comment by RNS101** [comment]
i have te same fault  :(

**Comment by Timnus** [comment]
attempted web install. nogo. tried offline install nogo. 
![neterror](https://user-images.githubusercontent.com/27913772/52522568-b2c67d00-2c4c-11e9-9d8c-fd0cff9ad104.JPG)

**Comment by RNS101** [comment]
i tried that thats the same message i get

**Comment by Timnus** [comment]
tried to run uninstall. still showing up in the programs list. tried to use cCleaner. same result.  program refuses to be able to be removed.

**Comment by Timnus** [comment]
tried to run uninstall. still showing up in the programs list. tried to use cCleaner. same result.  program refuses to be able to be removed. rebooted pc and still shows up in the apps list.
![appslist](https://user-images.githubusercontent.com/27913772/53707389-678b2e80-3df4-11e9-897e-3f47389aa714.JPG)

**Comment by RNS101** [comment]
Thansk for ur help tried that get a new fault now I the progam as never been installed  ☹

Ryan smith


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Timnus** [comment]
cannot do an install because of what is left behind. if programs shows as never installed then it needs to connect to current api in game

**Comment by Timnus** [comment]
tried to do install again..  install failed. attaching install log in zip format
[installEdEn.zip](https://github.com/msarilar/EDEngineer/files/3046376/installEdEn.zip)
[install.log](https://github.com/msarilar/EDEngineer/files/3046379/install.log)

**Comment by msarilar** [comment]
do you get the same uninstallation issues when uninstalling via `Control Panel\Programs\Programs and Features` ? 

![image](https://user-images.githubusercontent.com/5569959/55610461-40bd7080-5783-11e9-9822-6781cbb8de55.png)

**Comment by Timnus** [comment]
got it to remove via Revo. not showing up. 
![edenginner 2019-05-01 114858](https://user-images.githubusercontent.com/27913772/57029385-2dc58100-6c07-11e9-8302-a24329e515fa.png)

tried to run install again today get this log

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.6 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 461814
Setting value '461814 {int}' for property 'DotNet46Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet46Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.6 (x86 and x64)':
Property: [DotNet46Full_OSIntegrated] = 1 {int}
Property: [DotNet46Full_Release] = 461814 {int}
Running checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet46Full_Release' and value '393297': true
Result of checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet46Full_Release' and value '393297': true
Result of checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.6 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application'.

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.6 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 461814
Setting value '461814 {int}' for property 'DotNet46Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet46Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.6 (x86 and x64)':
Property: [DotNet46Full_OSIntegrated] = 1 {int}
Property: [DotNet46Full_Release] = 461814 {int}
Running checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX46\NDP46-KB3045557-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet46Full_Release' and value '393297': true
Result of checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet46Full_Release' and value '393297': true
Result of checks for command 'DotNetFX46\NDP46-KB3045560-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.6 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application'.

**Comment by Timnus** [comment]
PLATFORM VERSION INFO
	Windows 			: 10.0.17763.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3190.0 built by: NET472REL1LAST_C
	clr.dll 			: 4.7.3362.0 built by: NET472REL1LAST_C
	dfdll.dll 			: 4.7.3190.0 built by: NET472REL1LAST_C
	dfshim.dll 			: 10.0.17763.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///F:/Download/Games/EliteDangerous/EdEngineer/EDEngineer.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of F:\Download\Games\EliteDangerous\EdEngineer\EDEngineer.application resulted in exception. Following failure messages were detected:
		+ The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [5/1/2019 12:55:20 PM] : Activation of F:\Download\Games\EliteDangerous\EdEngineer\EDEngineer.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [5/1/2019 12:55:29 PM] System.Runtime.InteropServices.COMException
		- The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.GetAssemblyInformation(UInt32 Flags, IDefinitionIdentity DefinitionIdentity, Guid& riid)
			at System.Deployment.Internal.Isolation.Store.GetAssemblyManifest(UInt32 Flags, IDefinitionIdentity DefinitionIdentity)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestFromStore(DefinitionIdentity asmId)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestWithRetry(DefinitionIdentity asmId, TimeSpan retryInterval, Int32 maxRetryCount)
			at System.Deployment.Application.ComponentStore.GetSubscriptionStateInternal(DefinitionIdentity subId)
			at System.Deployment.Application.SubscriptionStore.GetSubscriptionStateInternal(SubscriptionState subState)
			at System.Deployment.Application.SubscriptionStore.CheckAndReferenceApplication(SubscriptionState subState, DefinitionAppId appId, Int64 transactionId)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
