### ISSUE TITLE
Error when install the program

### ISSUE THREAD

**Issue by denisvvf** [msarilar/EDEngineer#560]
I'm getting this error after try to launch the EDEngineer
http://prntscr.com/wmylz5

event viewer errors:
Application: EDEngineer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at EDEngineer.Properties.Settings.get_Language()
   at EDEngineer.Localization.Languages.InitLanguages()
   at EDEngineer.Localization.Languages.get_Instance()
   at EDEngineer.Views.Popups.ErrorWindow..ctor(System.Exception, System.String)
   at EDEngineer.App+<>c.<.ctor>b__1_0(System.Object, System.UnhandledExceptionEventArgs)

and 

Faulting application name: EDEngineer.exe, version: 1.0.0.0, time stamp: 0x5fdf65cd
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xe6477cce
Exception code: 0xe0434352
Fault offset: 0x0012a892
Faulting process id: 0x798
Faulting application start time: 0x01d6ea0231198666
Faulting application path: C:\Users\denis\AppData\Local\Apps\2.0\M96K8B2Y.X67\71OOHDH2.JK8\eden..tion_b9c6c2d0b4f2eae5_0001.0001_493a47489090e6e3\EDEngineer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ea68b34e-37a8-4274-8f57-ca2c7a90241f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by denisvvf** [comment]
Solved. Deleted all 2.0 directory inside local and installed again.
