### ISSUE TITLE
Bluescreen while opening, now it won't start. (Dump)

### ISSUE THREAD

**Issue by Repsycl3d** [msarilar/EDEngineer#564]
Raised vCore a bit in response, but anyway, I uninstalled it and tried to run a new, fresh setup.exe but get the same error. Here is the dump.

System.Windows.Markup.XamIParseException: Provide value on 'System.VVindows.Markup.StaticExtension' threw an exception.
> System.RefIection.TargetInvocationException: Exception has been thrown by the target of an invocation.
System. Configuration. ConfigurationErrorsException:
Configuration system failed to initialize -
> System.Configuration.ConfigurationErrorsException: hexadecimal valueOxOO, is an invalid character. Line 14, position I.
H7J.98Cx1 ODDZE4Y. ELI config line 14)
System.XmI.XmIException: , hexadecimal value OxOO, is an invalid character. Line 14, position I.
at System.XmI.XmITextReaderImpI.Throw(Exception e)
at System.XmI.XmITextReaderImpI.Throw(String res, String0 args)
at startPos, Int32& endPos, Int32& outOrChars)
at System.XmI.XmITextReaderImpI.ParseTextO
at System .XmI.XmITextReaderImpI.ParseEIementContentO
at System.XmI.XmITextReaderImpI.ReadO
at System.XmI.XmITextReader.ReadO
at System.XmI.XmITextReaderImpI.SkipO
at System.XmI.XmITextReader.SkipO
at System. Config uration .XmIUtiI. StrictSkipToNextEIement(ExceptionAction action)
at System.Configuration.aaseConfigurationRecord.ScanSectionsRecursive(XmILltiI xmlUtiI, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChiIdApps)
at System.Configuration.aaseConfigurationRecord.ScanSectionsRecursive(XmIUtiI xmlUtiI, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, aoolean skipInChiIdApps)
at System. Configuration.aaseConfigurationRecord. Scan Sections(XmILltiI xmlUtiIJ
at System. Configuration.aaseConfigurationRecord. InitConfigFromFiIeO
End of inner exception stack trace -
at System. Configuration. ConfigurationSchemaErrors.ThrowIfErrors(aooIean ignoreLocaI)
at System. Co eErrors(ConfigurationSchemaErrors schemaErrors)
at System. Configuration.aaseConfigurationRecord.ThrmvIfInitErrorsO
at System.Configuration.CIientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
End of inner exception stack trace
at System. Configuration. ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
at System. Configuration.InternaI.InternaIConfigRoot.OnConfigRemoved(InternaIConfigEventArgs e)
at System.Configuration.InternaI.InternaIConfigRoot.RemoveConfigImpI(String configPath, aaseConfigurationRecord configRecordJ
at System.Configuration.aaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
at System.Configuration.aaseConfigurationRecord.GetSection(String configKey)
at System. Co nfig u ration. ClientCo nfigurationSystem. System. Co nfigu ratio n. Internal. I InternalConfigSystem.GetSection(String sectionName)
at System.Configuration.ConfigurationManager.GetSection(String sectionName)
at System.Configuration.CIientSettingsStore.ReadSettings(String sectionName, aoolean isUserScoped)
at System.Configuration.LocaIFiIeSettingsProvider.GetPropertyVaIues(SettingsContext context, SettingsPropeftyCoIIection properties)
at System. Configuration. Settingsaase.GetPropertiesFromProvider(SettingsProvider provider)
at System. Configuration. eMIame(String propertyName)
at propertyName)
at System. Configuration.AppIicationSettingsaase.GetPropertyVaIue(String propertyName)
at System. Configuration propertyName)
at EDEngineer.Properties.Settings.get_Language0
at EDEngineer.LocaIization.Languages.InitLanguagesO
at EDEngineer.LocaIization. Languages. get_lnstanceo
End of inner exception stack trace
at System.RuntimeMethodHandIe.InvokeMethod(Object target, Objecto arguments, Signature sig, Boolean constructor)
at System.RefIection.RuntimeMethodInfo.UnsafeInvokeInternaI(Object obj, Objecto parameters, Objecto arguments)
at System.RefIection.RuntimeMethodInfo.Invoke(Object obj, aindingFIags invokeAttr, Binder binder, Objecto parameters, Culturelnfo culture)
at System.RefIection.RuntimePropertyInfo.GetVaIue(Object 0b], 8indingFIags invokeAttr, Binder binder, Objecto index, Culturelnfo culture)
at System.RefIection.RuntimePropertyInfo.GetVaIue(Object obj, Objecto index)
at System.Windows.Markup.StaticExtension.GetFieIdOrPropertyVaIueJype type, String name, Object& value)
at System.Windows.Markup.StaticExtension. ProvideVaIue(IServiceProvider serviceprovider)
at MS.InternaI.XamI.Runtime.CIrObjectRuntime.CaIIProvideVaIue(MarkupExtension me, IServiceProvider serviceprovider)
End of inner exception stack trace
at System.Windows.Markup.WpfXamILoader.Load(XamIReader xamIReader, IXamIObjectWriterFactory writerFactory, Boolean skipJournaIedProperties, Object rootObject, XamIObjectWriterSettings settings, uri baseUrl)
at System.Windows.Markup.WpfXamILoader.LoadaamI(XamIReader xamIReader, Boolean skipJournaIedProperties, Object rootObject, XamIAccessLeveI accessLeveI, uri baselJrl)
at System.Windows.Markup.XamIReader.LoadaamI(Stream stream, ParserContext parserContext, Object parent, Boolean closestream)
at System.Windows.AppIication.LoadaamIStreamWithSyncInfo(Stream stream, ParserContext pc)
at System.Windows.AppIication.LoadComponent(Uri resourceLocator, 8001ean bSkipJournaIedPropefties)
at System.VVindows.AppIication.DoStartupO
at System.Windows.AppIication.< . ctor> b _ I _O(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternaIReaICaII(DeIegate callback* Object args, Int32 numArgs)
at System.VVindows.Threading.ExceptionVVrapper.TryCatchWhen(Object source, Delegate callback* Object args, Int32 numArgs, Delegate catchHandIer)
System. Configuration. ConfigurationErrorsException: Configuration system failed to initialize -
> System.Configuration.ConfigurationErrorsException: hexadecimal value OXOO, is an invalid character. Line 14, position I.
H7J.98C\1 ODDZE4Y. ELI .o.omuser. config line 14)
> System.XmI.XmIException: ' I', hexadecimal value OXOO, is an invalid character. Line 14, position I.
at System.XmI.XmITextReaderImpI.Throw(Exception e)
at System.XmI.XmITextReaderImpI.Throw(String res, String0 args)
at startPos, Int32& endPos, Int32& outOrChars)
at System .XmI.XmITextReaderImpI.ParseTextO
at System .XmI.XmITextReaderImpI. ParseEIementContentO
at System .XmI.XmITextReaderImpI.ReadO
at System .XmI.XmITextReader.ReadO
at System.XmI.XmITextReaderImpI.SkipO
at System .XmI.XmITextReader.SkipO
at System. Configuration .Xm StrictSkipToNextEIement(ExceptionAction action)
at System.Configuration.aaseConfigurationRecord.ScanSectionsRecursive(XmIUtiI xmlUtiI, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChiIdApps)
at System.Configuration.aaseConfigurationRecord.ScanSectionsRecursive(XmIUtiI xmlUtiI, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, aoolean skipInChiIdApps)
at System. Configuration.aaseConfigurationRecord. ScanSections(XmIUtiI xmlUtiIJ
at System. ImtConfigFromFiIeO
- End of inner exception stack trace
at System Configuration. ConfigurationSchemaErrors.ThrowIfErrors(aooIean ignoreLocaIJ
at System Configuration.aaseConfigurationRecord.T hrowIfPars eErrors(ConfigurationSchemaErrors schemaErrorsJ
at System. Configuration.aaseConfigurationRecord.ThrowIfInitErrorsO
at System.Configuration.CIientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
End of inner exception stack trace
at System. Configuration. ConfigurationManager. PrepareConfigSystemO
at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
at System.Configuration.CIientSettingsStore.ReadSettings(String sectionName, Boolean isUserScopedJ
at System.Configuration.LocaIFiIeSettingsProvider.GetPropertyVaIues(SettingsContext context, SettingsPropertyCoIIection properties)
at System. Configuration. Settingsaase.GetPropertiesFromProvider(SettingsProvider provider)
at System. Configuration. Settingsaase. GetPropertyVaIueMIame(String propertyName)
at propertyName)
at System. Configuration GetPropertyVaIue(String propertyName)
at System. propertyName)
at EDEngineer.Properties.Settings.get_LanguageO
at EDEngineer.LocaIization.Languages.InitLanguagesO
at EDEngineer.LocaIization.Languages.get_InstanceO
at EDEngineer.Views.Popups.ErrorWindow..ctor(Exception exception, String title)
at EDEngineer.App.< > .ctor> (Object o, DispatcherUnhandIedExceptionEventArgs e)
at System.Windows.Threading.DispatcherUnhandIedExceptionEventHandIer.Invoke(Object sender, DispatcherUnhandIedExceptionEventArgs e)
at System.VVindows.Threading.Dispatcher.CatchException(Exception e)
at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandIer)
at System.VVindows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandIer)
at System.Windows.Threading.DispatcherOperation.InvokeImp10
at System erOperation.InvokeInSecurityContext(Object state)
at MS. Internal. CulturePreservingExecutionCo ntext. CallbackWrapper(Object obj)
at System.Threading.ExecutionContext.RunInternaI(ExecutionContext executionContext, ContextCaIIback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCaIIback callback, Object state, aoolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCaIIback callback, Object state)
at MS.InternaI.CuIturePreservingExecutionContext.Run(CuIturePreservingExecutionContext executionContext, ContextCaIIback callback, Object state)
at System.Windows.Threading.DispatcherOperation.InvokeO
at System.Windows.Threading.Dispatcher.ProcessQueueO
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr IParam, 8001ean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr IParam, aoolean& handled)
at MS.Win32.HwndSubcIass.DispatcherCaIIbackOperation(Object o)
at System.VVindows.Threading.ExceptionWrapper.InternaIReaICaII(DeIegate callback* Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback* Object args, Int32 numArgs, Delegate catchHandIer)

**Comment by msarilar** [comment]
most likely the settings file got corrupted when you got your bsod

have you tried reinstalling?

**Comment by Repsycl3d** [comment]
Yes.I used the add/remove programs app in Windows to uninstall, then ran
setup.exe. Same result. Then I deleted the EDengineer folder in
programdata. Still the same error.

**Comment by Repsycl3d** [comment]
Any updates on this? I suspect I just need to clean out the old data, but
for some reason it isn't removed properly when the program is uninstalled.
Any pointers? I'd like to use this utility again without nuking my Windows
install.

**Comment by msarilar** [comment]
I think you might need to delete your setting file manually
it should be somewhere in AppData, once you delete it you should be able to start the app

**Comment by Repsycl3d** [comment]
I deleted all the edengineer related things and re-installed. It always
gives that same error. Do you know what it's saying in the dump? I don't
understand it.

**Comment by msarilar** [comment]
yeah the line:

```
System.Configuration.ConfigurationErrorsException: hexadecimal valueOxOO, is an invalid character. Line 14, position I.
H7J.98Cx1 ODDZE4Y. ELI config line 14)
```

indicates that the config file is corrupted (the file is located in an obfuscated directory in appdata)

i've pushed something that will try and fix the file if there's an error, no guarantee this will work but let me know

**Comment by Repsycl3d** [comment]
IT'S ALIIIIIVE!!! Thank you!!! I was flying to the engineers, looking at
the upgrades and writing down the materials I would need on a notepad to go
farm for. Thank you again!!!
