### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Wullailhuit** [msarilar/EDEngineer#606]
I'm trying to install the latest version (using the exe) , it gets as far as the large 'ED ENGINEER' box with rotating balls a large pause and then throws this up in a seperate box.

I've removed all the data , uninstalled it etc etc as suggested in the 'have issues list' to no avail.

System.AggregateException: One or more errors occurred. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EDEngineer.Models.Operations.UpgradeOperation.GetEquipment(State state)
   at EDEngineer.Models.Operations.UpgradeOperation.Mutate(State state)
   at EDEngineer.Views.CommanderViewModel.MutateState(JournalEntry entry)
   at EDEngineer.Views.CommanderViewModel.ApplyEventsToSate(IEnumerable`1 allLogs)
   at EDEngineer.Views.MainWindowViewModel.ApplyEvents(Tuple`2 logs)
   at EDEngineer.Views.MainWindowViewModel.LoadState()
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages, String directory)
   at EDEngineer.Views.MainWindow.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EDEngineer.Models.Operations.UpgradeOperation.GetEquipment(State state)
   at EDEngineer.Models.Operations.UpgradeOperation.Mutate(State state)
   at EDEngineer.Views.CommanderViewModel.MutateState(JournalEntry entry)
   at EDEngineer.Views.CommanderViewModel.ApplyEventsToSate(IEnumerable`1 allLogs)
   at EDEngineer.Views.MainWindowViewModel.ApplyEvents(Tuple`2 logs)
   at EDEngineer.Views.MainWindowViewModel.LoadState()
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages, String directory)
   at EDEngineer.Views.MainWindow.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by msarilar** [comment]
would you mind uploading your latest logs here? I think you have an equipment that is not referenced in https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/equipment.json added by @jpacelli62

maybe the parsing should be made more robust (not crash if the equipment isn't found in the json)

I can look into this later today

**Comment by Wullailhuit** [comment]
[Journal.210608142638.01.log](https://github.com/msarilar/EDEngineer/files/6618149/Journal.210608142638.01.log)
[Journal.210608111849.01.log](https://github.com/msarilar/EDEngineer/files/6618150/Journal.210608111849.01.log)
[Journal.210608060109.01.log](https://github.com/msarilar/EDEngineer/files/6618151/Journal.210608060109.01.log)

**Comment by PiezPiedPy** [comment]
I'm getting the exact same thing.

**Comment by jpacelli62** [comment]
According to the logs, I only see an update of the Dominator suit but the application does not crash for me.
Could you also send your latests logs @PiezPiedPy  please?

**Comment by msarilar** [comment]
won't fix the issue but I pushed an update to avoid crashing the app, you'll get a popup instead (ctrlC the popup, it will copy the message to the clipboard so you can paste it here)

**Comment by PiezPiedPy** [comment]
Just tried and the popup gave the string 'wpn_m_submachinegun_kinetic_fauto'

 interestingly I had also just upgraded my C-44 to G2 just before installing the engineer update.

another thing is that the capitalization of the string in the equipment.json file does not match the string in the error, see   https://github.com/msarilar/EDEngineer/blob/63a429b385d485689ba9301a9a20f9e0238ed052/EDEngineer/Resources/Data/equipment.json#L46

**Comment by jpacelli62** [comment]
I'm merging for a merge request, i'ts a case issue.
will be fixed soon

**Comment by PiezPiedPy** [comment]
I assumed it was a case issue, thx for the speedy response 😎

**Comment by Wullailhuit** [comment]
---------------------------
Warning
---------------------------
Unknown equipment wpn_s_pistol_plasma_charged. Ctrl+C while this messagebox is on focus then kindly report this on github
---------------------------
OK   
---------------------------

**Comment by PiezPiedPy** [comment]
logs as requested 

[Journal.210607174327.01.log](https://github.com/msarilar/EDEngineer/files/6618639/Journal.210607174327.01.log)
[Journal.210604005752.01.log](https://github.com/msarilar/EDEngineer/files/6618642/Journal.210604005752.01.log)
