### ISSUE TITLE
System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException

### ISSUE THREAD

**Issue by killadark** [msarilar/EDEngineer#659]
Cannot launch the app as it keeps saying above issue... when i check ram usage it crashes around 3.1gb used and over 10gb still free in ram. I have a 30gb page file also.

System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.Append(Char[] value, Int32 startIndex, Int32 charCount)
   at System.IO.StreamReader.ReadLine()
   at EDEngineer.Models.Utils.LogWatcher.ReadLinesWithoutLock(String file)
   at EDEngineer.Models.Utils.LogWatcher.RetrieveAllLogs()
   at EDEngineer.Views.MainWindowViewModel.LoadState()
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages, String directory)
   at EDEngineer.Views.MainWindow.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.Append(Char[] value, Int32 startIndex, Int32 charCount)
   at System.IO.StreamReader.ReadLine()
   at EDEngineer.Models.Utils.LogWatcher.ReadLinesWithoutLock(String file)
   at EDEngineer.Models.Utils.LogWatcher.RetrieveAllLogs()
   at EDEngineer.Views.MainWindowViewModel.LoadState()
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages, String directory)
   at EDEngineer.Views.MainWindow.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by msarilar** [comment]
could you update the app and give it a go again?

**Comment by killadark** [comment]
Working fine now thank you.
