### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by mrstry** [msarilar/EDEngineer#725]
System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonSerializer.CreateDefault()
   at Newtonsoft.Json.JsonSerializer.CreateDefault(JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at EDEngineer.Views.CommanderViewModel.<ApplyEventsToSate>b__34_0(String l)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EDEngineer.Views.CommanderViewModel.ApplyEventsToSate(IEnumerable`1 allLogs)
   at EDEngineer.Views.CommanderViewModel.LoadLogs(IEnumerable`1 events)
   at EDEngineer.Views.MainWindowViewModel.<>c__DisplayClass20_2.<LoadState>b__3(CommanderViewModel c)
   at EDEngineer.Views.CommanderViewModel..ctor(String commanderName, Action`1 loadAction, Languages languages, List`1 entryDatas, List`1 equipments)
   at EDEngineer.Views.MainWindowViewModel.LoadState()
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages, String directory)
   at EDEngineer.Views.MainWindow.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonSerializer.CreateDefault()
   at Newtonsoft.Json.JsonSerializer.CreateDefault(JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at EDEngineer.Views.CommanderViewModel.<ApplyEventsToSate>b__34_0(String l)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EDEngineer.Views.CommanderViewModel.ApplyEventsToSate(IEnumerable`1 allLogs)
   at EDEngineer.Views.CommanderViewModel.LoadLogs(IEnumerable`1 events)
   at EDEngineer.Views.MainWindowViewModel.<>c__DisplayClass20_2.<LoadState>b__3(CommanderViewModel c)
   at EDEngineer.Views.CommanderViewModel..ctor(String commanderName, Action`1 loadAction, Languages languages, List`1 entryDatas, List`1 equipments)
   at EDEngineer.Views.MainWindowViewModel.LoadState()
   at EDEngineer.Views.MainWindowViewModel..ctor(Languages languages, String directory)
   at EDEngineer.Views.MainWindow.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by mrstry** [comment]
![Uploading edengineer.png…]()

**Comment by mrstry** [comment]
the problem was on save data 
the problem is solved

**Comment by yucatan** [comment]
How did you solve it?
